name: lightforest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  table_calendar: ^3.0.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lightforest_main.png
    - assets/lightforest_appbar_logo.png
    - assets/bible_icon.png
    - assets/praying_hand_icon.png
    - assets/exercise_icon.png
    - .env
